### ISSUE TITLE
extractSMR function

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/SoilTaxonomy#34]
Probably simplest to search subgroup for those formative elements identifying SMR, when possible. Ideas:

  * search order → suborder → greatgroup → subgroup, assemble matrix of matching SMR
  * possible for SMR (suborder) + intergrade information from lower levels

**Comment by brownag** [comment]
This is done. I think working with "soil moisture subclasses" should be a different function as there is a lot more nuance to determining that from e.g. a subgroup-level taxon
