### ISSUE TITLE
SubOrderFormativeElements() and histosols

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/SoilTaxonomy#6]
The current strategy breaks down with "fibristels" "folistels"  "hemistels"  "glacistels" "sapristels", due to the contraction of "hist" to "ist".

Some ideas:
   * custom look-up for these taxa
   * use the strategy employed by `SubGroupFormativeElements()` where matching is performed on the formative elements vs. exact matching of parent taxa

**Comment by brownag** [comment]
This issue is resolved since the use of the lookup table using letter codes to denote parent-child relationships with little-to-no pattern matching required. Came with reorganization of the package in #14
