### ISSUE TITLE
GreatGroupFormativeElements() and multiple matches

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/SoilTaxonomy#7]
Need to use the same strategy as `SubOrderFormativeElements()`. 

```r
GreatGroupFormativeElements('acrustoxic kanhaplustults')
```

This has to do with `map_int()` expecting a single value / element.
```
  x
 1. +-SoilTaxonomy::GreatGroupFormativeElements("acrustoxic kanhaplustults")
 2. | \-purrr::map_int(loc.start, .safelyPickNotNA)
 3. \-purrr:::stop_bad_element_vector(...)
 4.   \-purrr:::stop_bad_vector(...)
 5.     \-purrr:::stop_bad_type(...)
```

**Comment by brownag** [comment]
This issue is resolved since {purrr} dependency was dropped. Came with reorganization of the package in #14 and use of lookup table rather than pattern matching to determine parent-child relationships
